/**
Local
L1 版本本地接口 L1版本
*/

export const CLIENT_LIST_BOOK_L1 = 'CLIENT_LIST_BOOK_L1'
export const LIST_BOOK_L1 = 'LIST_BOOK_L1'
export const TESTER_RACE = 'TESTER_RACE'
export const LIST_CHAPTER_L1 = 'LIST_CHAPTER_L1'
export const LIST_VOLUMES_L1 = 'LIST_VOLUMES_L1'

export const LIST_LOCAL_AND_ONLINE_BOOKS = 'LIST_LOCAL_AND_ONLINE_BOOKS'
export const LIST_LOCAL_AND_ONLINE_CHAPTERS = 'LIST_LOCAL_AND_ONLINE_CHAPTERS'
export const SET_BOOKS_L1 = 'SET_BOOKS_L1'
export const GET_BOOKS_L1 = 'GET_BOOKS_L1'

export const GET_OVER_BOOK_L1 = 'GET_OVER_BOOK_L1'
export const GET_NOT_OVER_BOOK_L1 = 'GET_NOT_OVER_BOOK_L1'

export const GET_EDITOR_BOOKS_L1 = 'GET_EDITOR_BOOKS_L1'
export const ADD_OPEN_BOOK_TO_EDITOR_L1 = 'ADD_OPEN_BOOK_TO_EDITOR_L1'

export const LIST_LOCAL_AND_ONLINE_VOLUMES = 'LIST_LOCAL_AND_ONLINE_VOLUMES'
export const SET_VOLUMES_TO_BOOK_IN_EDITOR_L1 = 'SET_VOLUMES_TO_BOOK_IN_EDITOR_L1'
export const GET_BOOK_VOLUMES_L1 = 'GET_BOOK_VOLUMES_L1'
export const GET_VOLUME_CHAPTERS_L1 = 'GET_VOLUME_CHAPTERS_L1'
export const GET_CURRENT_BOOK_VOLUMES_L1 = 'GET_CURRENT_BOOK_VOLUMES_L1'
// export const GET_CURRENT_BOOK_L1 = 'GET_CURRENT_BOOK_L1'
export const GET_CURRENT_BOOK_ID_L1 = 'GET_CURRENT_BOOK_ID_L1'
export const SET_CURRENT_BOOK_ID_L1 = 'SET_CURRENT_BOOK_ID_L1'
export const SET_CHAPTERS_TO_VOLUME_IN_EDITOR_L1 = 'SET_CHAPTERS_TO_VOLUME_IN_EDITOR_L1'
export const GET_CHAPTER_CONTENT_L1 = 'GET_CHAPTER_CONTENT_L1'



export const SYNC_UPDATE_BOOK_CONTENT_L1 = 'SYNC_UPDATE_BOOK_CONTENT_L1'
// 修改vuex书籍模块数据
export const SET_BOOK_CONTENT_L1 = 'SET_BOOK_CONTENT_L1'
export const ADD_BOOK_L1 = 'ADD_BOOK_L1'
export const DELETE_BOOK_L1 = 'DELETE_BOOK_L1'
export const ADD_VOLUME_TO_BOOK_L1 = 'ADD_VOLUME_TO_BOOK_L1'
export const ADD_CHAPTER_TO_VOLUME_L1 = 'ADD_CHAPTER_TO_VOLUME_L1'

export const CREATE_NEW_BOOK_L1 = 'CREATE_NEW_BOOK_L1'
export const CREATE_NEW_VOLUME_L1 = 'CREATE_NEW_VOLUME_L1'
export const CREATE_NEW_CHAPTER_L1 = 'CREATE_NEW_CHAPTER_L1'

//新建章节结果, 用于处理导入章节的逻辑 (目前由于使用CREATE_NEW_CHAPTER_L1 替代 CHAPTER_ADD_BOOK, 原有逻辑已失效)
export const CREATE_CHAPTER_RESULT_L1 = 'CREATE_CHAPTER_RESULT_L1'



/**
 * ADD_BOOK    添加书本
 * LIST_BOOK   获取书本列表
 * USER_CHANGE_BOOK    修改书本信息
 * SYNC_USER_CHANGE_BOOK  从本地库中更新单本书
 * CLIENT_LIST_BOOK    获取本地数据库的书本列表
 * INFO_BOOK   将bookList表转换为JSON
 * VOLUME_ADD_BOOK   新建卷
 * CHAPTER_ADD_BOOK  新建章
 * DELETE_BOOK       删除书
 * VOLUME_DEL_BOOK   删除卷
 * VOLUME_DEL_BOOK_VERSION 删除卷，更改全书字数，更新version
 * CHAPTER_DEL_BOOK  删除章
 * CHAPTER_DEL_UPLOAD_VERSION 删除章节，更改全书字数，更新version
 * CHAPTER_UP_BOOK   上移一章
 * OPEN_BOOK   打开书本
 * SELECT_BOOK  选择书本
 * UPDATE_ACTION_BOOK     用户手动创建(修改)书/卷/章内容，被动推送消息
 * GET_OVER_BOOK      获取已完结书本列表
 * GET_NOT_OVER_BOOK   获取未完结书本列表
 * BOOK_MESSAGE      书本接口操作的返回信息，和状态值
 * GET_BOOK_MESSAGE   获取书本接口操作的返回信息，和状态值
 * QUERY_UPDATE_TIME  查询书本模块更新的update_time值
 * CHAPTER_CONTENT_SYNC  同步卷下图书内容列表
 * CLOSE_BOOK        关闭书本
 * CHANGE_TITLE_BOOK 修改卷章名称
 * CHANGE_TITLE_BOOK_VERSION 修改卷章名称后更新version
 * RESET_BOOK_MODULE 清除书本模块内存储数据
 * BOOK_CHANGE_WORD_COUNT  本章字数和本书字数更新
 * BOOK_CHANGR_WORD_VERSION  本章字数和本书字数更新后改变version
 */
export const ADD_BOOK = 'ADD_BOOK'
export const CLIENT_LIST_BOOK = 'CLIENT_LIST_BOOK'
export const LIST_BOOK = 'LIST_BOOK'
export const USER_CHANGE_BOOK = 'USER_CHANGE_BOOK'
export const SYNC_USER_CHANGE_BOOK = 'SYNC_USER_CHANGE_BOOK'
export const VOLUME_ADD_BOOK = 'VOLUME_ADD_BOOK'
export const CHAPTER_ADD_BOOK = 'CHAPTER_ADD_BOOK'
export const CHAPTER_DEL_BOOK = 'CHAPTER_DEL_BOOK'
export const CHAPTER_UP_BOOK = 'CHAPTER_UP_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const VOLUME_DEL_BOOK = 'VOLUME_DEL_BOOK'
export const VOLUME_DEL_BOOK_VERSION= 'VOLUME_DEL_BOOK_VERSION'
export const CHAPTER_DEL_UPLOAD_VERSION = 'CHAPTER_DEL_UPLOAD_VERSION'
export const INFO_BOOK = 'INFO_BOOK'
export const OPEN_BOOK = 'OPEN_BOOK'
export const SELECT_BOOK = 'SELECT_BOOK'
export const UPDATE_ACTION_BOOK = 'UPDATE_ACTION_BOOK'
export const GET_OVER_BOOK = 'GET_OVER_BOOK'
export const GET_NOT_OVER_BOOK = 'GET_NOT_OVER_BOOK'
export const BOOK_MESSAGE = 'BOOK_MESSAGE'
export const GET_BOOK_MESSAGE = 'GET_BOOK_MESSAGE'
export const QUERY_UPDATE_TIME = 'QUERY_UPDATE_TIME'
export const CHAPTER_CONTENT_SYNC = 'CHAPTER_CONTENT_SYNC'
export const CLOSE_BOOK = 'CLOSE_BOOK'
export const CHANGE_TITLE_BOOK = 'CHANGE_TITLE_BOOK'
export const CHANGE_TITLE_BOOK_VERSION = 'CHANGE_TITLE_BOOK_VERSION'
export const RESET_BOOK_MODULE = 'RESET_BOOK_MODULE'
export const BOOK_CHANGE_WORD_COUNT = 'BOOK_CHANGE_WORD_COUNT'
export const BOOK_CHANGR_WORD_VERSION = 'BOOK_CHANGR_WORD_VERSION'


/**
 * POPUPS_STATUS   获取弹窗显示状态
 * IS_POPUPS   显示关闭弹窗
 */
/*export const POPUPS_STATUS = 'POPUPS_STATUS'
 export const IS_POPUPS = 'IS_POPUPS'*/


/**
 *   user.js
 *   USER_SIGNIN :登录
 *   USER_CODE_SIGNIN :验证码登录
 *   USER_CODE_VERIFY :验证码验证
 *   SIGNUP_PHONE_IS_REGIST 手机是否注册
 *   SIGNUP_PHONE_REGIST_STATUS 获取手机是否注册状态
 *   USER_REGISTER 用户普通注册
 *   LOGIN_CODE_STATUS 获取验证码登录返回状态
 *   UP_LOGIN_CODE_STATUS 保存验证码登录返回状态*
 *   LOGIN_PASSWORD_STATUS 获取密码登录返回状态
 *   UP_LOGIN_PASSWORD_STATUS 保存密码登录返回状态
 *   GET_USET_DATA:  返回用户基本信息
 *   USER_DOWNLOAD_SQL  下载用户sql表
 *   USER_OPEN_DB  绑定本地DB库
 *   USER_CHANGE_DATA    修改用户基本信息
 *   USER_LOGOUT    用户登出
 *   VERIFY_TOKEN  验证token是否失效
 *   RESET_USER_MODULE  清除用户模块内存储数据
 * */
export const USER_SIGNIN = 'user/USER_SIGNIN'
export const USER_CODE_SIGNIN = 'user/USER_CODE_SIGNIN'
export const USER_CODE_VERIFY = 'user/USER_CODE_VERIFY'
export const SIGNUP_PHONE_IS_REGIST = 'user/SIGNUP_PHONE_IS_REGIST'
export const SIGNUP_PHONE_REGIST_STATUS = 'user/SIGNUP_PHONE_REGIST_STATUS'
export const USER_REGISTER = 'user/USER_REGISTER'
export const LOGIN_CODE_STATUS = 'user/LOGIN_CODE_STATUS'
export const UP_LOGIN_CODE_STATUS = 'user/UP_LOGIN_CODE_STATUS'
export const LOGIN_PASSWORD_STATUS = 'user/LOGIN_PASSWORD_STATUS'
export const UP_LOGIN_PASSWORD_STATUS = 'user/UP_LOGIN_PASSWORD_STATUS'
export const GET_USET_DATA = 'user/GET_USET_DATA'
export const USER_DOWNLOAD_SQL = 'user/USER_DOWNLOAD_SQL'
export const USER_OPEN_DB = 'user/USER_OPEN_DB'
export const USER_CHANGE_DATA = 'user/USER_CHANGE_DATA'
export const USER_LOGOUT = 'user/USER_LOGOUT'
export const VERIFY_TOKEN = 'user/VERIFY_TOKEN'
export const RESET_USER_MODULE = 'RESET_USER_MODULE'


/**
 * NOTE_LIST   获取notes灵感随笔列表
 * ADD_NOTE     添加随笔
 * DELETE_NOTE      删除随笔
 * UPDATE_NOTE_CONTENT      修改随笔内容
 * UPDATE_NOTE_SELECTED     修改随笔选中状态
 * RESET_NOTE_MODULE    清除灵感随笔模块内存储数据
 */
export const NOTE_LIST = 'NOTE_LIST'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const UPDATE_NOTE_CONTENT = 'UPDATE_NOTE_CONTENT'
export const UPDATE_NOTE_SELECTED = 'UPDATE_NOTE_SELECTED'
export const UPDATE_NOTE_VERSION = 'UPDATE_NOTE_VERSION'
export const UPDATE_NOTE_ISUPLOAD = 'UPDATE_NOTE_ISUPLOAD'
export const NOTE_SYNC = 'NOTE_SYNC'
export const RESET_NOTE_MODULE = 'RESET_NOTE_MODULE'

/**
 * UPDATE_RANDOM_NAME       更新随机取名名字列表
 * RANDOM_NAME_LIST     获取取名列表
 * RESET_RANDOMNAME_MODULE   清除随机取名模块内存储数据
 */
export const UPDATE_RANDOM_NAME_CONTENT = 'UPDATE_RANDOM_NAME_CONTENT'
export const UPDATE_RANDOM_NAME_VERSION = 'UPDATE_RANDOM_NAME_VERSION'
export const UPDATE_RANDOM_NAME_ISUPLOAD = 'UPDATE_RANDOM_NAME_ISUPLOAD'
export const RANDOM_NAME_LIST = 'RANDOM_NAME_LIST'
export const RESET_RANDOMNAME_MODULE = 'RESET_RANDOMNAME_MODULE'

/**
 * SENSITIVE_WORDS      敏感词
 * UPDATE_SENSITIVE_WORDS   自定义敏感词
 * RESET_SENSITIVEWORD_MODULE   清除敏感词模块内存储数据
 */
export const SENSITIVE_WORDS = 'SENSITIVE_WORDS'
export const UPDATE_SENSITIVE_WORDS_CONTENT = 'UPDATE_SENSITIVE_WORDS_CONTENT'
export const UPDATE_SENSITIVE_WORDS_VERSION = 'UPDATE_SENSITIVE_WORDS_VERSION'
export const UPDATE_SENSITIVE_WORDS_ISUPLOAD = 'UPDATE_SENSITIVE_WORDS_ISUPLOAD'
export const RESET_SENSITIVEWORD_MODULE = 'RESET_SENSITIVEWORD_MODULE'
/**
 * RESET_SETTING_MODULE 清除用户插件设置模块内存储数据 
 * */  
export const RESET_SETTING_MODULE = 'RESET_SETTING_MODULE'



/**
 * outline/OUTLINE_TEXT 文本大纲
 * */  
export const OUTLINE_TEXT = 'outline/OUTLINE_TEXT'

/** 
 * RESET_RANK_MODULE 情况rank模块下数据
 * */ 
export const RESET_RANK_MODULE = 'RESET_RANK_MODULE'